### ISSUE TITLE
Document BsonValueRegex constructor

### ISSUE THREAD

**Issue by knsd** [lambda-llama/bresson#1]
Currently it looks `BsonValueRegex !Text !Text` and it's not obvious what first and second Text mean.

**Comment by knsd** [comment]
Second `Text` is regex options, so it's better to provide separate datatype for them and use.

**Comment by superbobry** [comment]
`newtype` you mean? 

Also, we better have some roadmap for `bresson` and "the new" MongoDB driver or it's never going to happen, what do you think?

**Comment by knsd** [comment]
No, I mean something like `data RegexOption = RegexOptionCaseInsensitive | RegexOptionMultiline …` and `type RegexOptions = BitSet RegexOption`

**Comment by knsd** [comment]
@superbobry, please review 80528ff
