### ISSUE TITLE
ToBson and FromBson instances for Words

### ISSUE THREAD

**Issue by knsd** [lambda-llama/bresson#12]

**Comment by superbobry** [comment]
BSON doesn't define any unsigned integer data type, which means that you really want implicit coercions to and from `Int`, right?

**Comment by knsd** [comment]
Well I think we can provide instances for Word8 and Word16 at least.

**Comment by superbobry** [comment]
This will still mean unsigned <-> signed coercions, are you okay with that?

**Comment by knsd** [comment]
Ok, I understand finally what you mean.
