### ISSUE TITLE
Should we implement ToBson and FromBson instances for Integer?

### ISSUE THREAD

**Issue by knsd** [lambda-llama/bresson#13]
Via BsonValueBinary for example

**Comment by superbobry** [comment]
How do you expect to perform queries with comparisons (`$gt`, `$lt`) on that field? Are binaries compared lexicographically?

**Comment by knsd** [comment]
You are right, even we can correctly implement `$gt` and `$lt`, it's very non-obvious how to implement and work with something like `$inc`.
