### ISSUE TITLE
Safe aeson-style getters

### ISSUE THREAD

**Issue by superbobry** [lambda-llama/bresson#14]
Why don't we drop `!?` in favour of a safer approach, [implemented](http://hackage.haskell.org/packages/archive/aeson/0.6.1.0/doc/html/Data-Aeson-Types.html#v:parse) in `aeson`. The idea is to introduce a `Parser` monad, responsible for extracting values of arbitrary data types from BSON data. Example:

``` haskell
parsePerson = flip parseMaybe result $ \obj -> do
     age  <- obj .: "age"
     name <- obj .: "name"
     return (name ++ ": " ++ show (age*2))
```

**Comment by knsd** [comment]
What's wrong with `Either InvalidBson` monad?

``` haskell
parsePerson obj = do
     age  <- obj !? "age"
     name <- obj !? "name"
     return (name ++ ": " ++ show (age*2))
```

Is there any additional `Parser` benefit with the exception of safety?

**Comment by superbobry** [comment]
`aeson` uses `Parser` to support multiple possible behaviours `Maybe`, `Either` etc. Can we accomplish the same with `failure`?

**Comment by knsd** [comment]
Done.
