### ISSUE TITLE
Is something like genObjectId should be implemented here?

### ISSUE THREAD

**Issue by knsd** [lambda-llama/bresson#7]
http://hackage.haskell.org/packages/archive/bson/0.2.2/doc/html/Data-Bson.html#v:genObjectId

**Comment by superbobry** [comment]
Yup, we might need this in MongoDB driver.

**Comment by knsd** [comment]
Implemented in lambda-llama/mnogo@b287cc7873f45daa7af466b22b4715d08df6e868
